{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6ef0198d",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Individual Programming Assignment 3\n",
    "\n",
    "70 points\n",
    "\n",
    "This assignment will develop your ability to manipulate data.\n",
    "'''\n",
    "\n",
    "def relationship_status(from_member, to_member, social_graph):\n",
    "    '''Relationship Status.\n",
    "    20 points.\n",
    "\n",
    "    Let us pretend that you are building a new app.\n",
    "    Your app supports social media functionality, which means that users can have\n",
    "    relationships with other users.\n",
    "\n",
    "    There are two guidelines for describing relationships on this social media app:\n",
    "    1. Any user can follow any other user.\n",
    "    2. If two users follow each other, they are considered friends.\n",
    "\n",
    "    This function describes the relationship that two users have with each other.\n",
    "\n",
    "    Please see \"assignment-4-sample-data.py\" for sample data. The social graph\n",
    "    will adhere to the same pattern.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    from_member: str\n",
    "        the subject member\n",
    "    to_member: str\n",
    "        the object member\n",
    "    social_graph: dict\n",
    "        the relationship data\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        \"follower\" if fromMember follows toMember,\n",
    "        \"followed by\" if fromMember is followed by toMember,\n",
    "        \"friends\" if fromMember and toMember follow each other,\n",
    "        \"no relationship\" if neither fromMember nor toMember follow each other.\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    if to_member in social_graph[from_member][\"following\"] and from_member in social_graph[to_member][\"following\"]:\n",
    "        return \"friend\"\n",
    "    elif from_member in social_graph[to_member][\"following\"]:\n",
    "        return \"followed by\"\n",
    "    elif to_member in social_graph[from_member][\"following\"]:\n",
    "        return \"follower\"\n",
    "    else:\n",
    "        return \"no relationship\"\n",
    "\n",
    "social_graph = {\n",
    "    \"@bongolpoc\":{\"first_name\":\"Joselito\",\n",
    "                  \"last_name\":\"Olpoc\",\n",
    "                  \"following\":[\n",
    "                  ]\n",
    "    },\n",
    "    \"@joaquin\":  {\"first_name\":\"Joaquin\",\n",
    "                  \"last_name\":\"Gonzales\",\n",
    "                  \"following\":[\n",
    "                      \"@chums\",\"@jobenilagan\"\n",
    "                  ]\n",
    "    },\n",
    "    \"@chums\" : {\"first_name\":\"Matthew\",\n",
    "                \"last_name\":\"Uy\",\n",
    "                \"following\":[\n",
    "                    \"@bongolpoc\",\"@miketan\",\"@rudyang\",\"@joeilagan\"\n",
    "                ]\n",
    "    },\n",
    "    \"@jobenilagan\":{\"first_name\":\"Joben\",\n",
    "                   \"last_name\":\"Ilagan\",\n",
    "                   \"following\":[\n",
    "                    \"@eeebeee\",\"@joeilagan\",\"@chums\",\"@joaquin\"\n",
    "                   ]\n",
    "    },\n",
    "    \"@joeilagan\":{\"first_name\":\"Joe\",\n",
    "                  \"last_name\":\"Ilagan\",\n",
    "                  \"following\":[\n",
    "                    \"@eeebeee\",\"@jobenilagan\",\"@chums\"\n",
    "                  ]\n",
    "    },\n",
    "    \"@eeebeee\":  {\"first_name\":\"Elizabeth\",\n",
    "                  \"last_name\":\"Ilagan\",\n",
    "                  \"following\":[\n",
    "                    \"@jobenilagan\",\"@joeilagan\"\n",
    "                  ]\n",
    "    },\n",
    "}    \n",
    "def tic_tac_toe(board):\n",
    "    '''Tic Tac Toe.\n",
    "    25 points.\n",
    "\n",
    "    Tic Tac Toe is a common paper-and-pencil game.\n",
    "    Players must attempt to successfully draw a straight line of their symbol across a grid.\n",
    "    The player that does this first is considered the winner.\n",
    "\n",
    "    This function evaluates a tic tac toe board and returns the winner.\n",
    "\n",
    "    Please see \"assignment-4-sample-data.py\" for sample data. The board will adhere\n",
    "    to the same pattern. The board may by 3x3, 4x4, 5x5, or 6x6. The board will never\n",
    "    have more than one winner. The board will only ever have 2 unique symbols at the same time.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    board: list\n",
    "        the representation of the tic-tac-toe board as a square list of lists\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the symbol of the winner or \"NO WINNER\" if there is no winner\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    for row in board:\n",
    "        if len(set(row)) == 1 and row[0] != \"\":\n",
    "            return row[0]\n",
    "    for col in range(len(board)):\n",
    "        if len(set(row[col] for row in board)) == 1 and board[0][col] != \"\":\n",
    "            return board[0][col]\n",
    "    if len(set(board[i][i] for i in range(len(board)))) == 1 and board[0][0] != \"\":\n",
    "        return board[0][0]\n",
    "    if len(set(board[i][len(board)-1-i] for i in range(len(board)))) == 1 and board[0][len(board)-1] != \"\":\n",
    "        return board[0][len(board)-1]\n",
    "\n",
    "    return \"NO WINNER\"\n",
    "\n",
    "\n",
    "board1 = [\n",
    "    ['X', 'X', 'O'], ['O', 'X', 'O'], ['O', '', 'X'],\n",
    "]\n",
    "\n",
    "board2 = [\n",
    "    ['X', 'X', 'O'], ['O', 'X', 'O'], ['', 'O', 'X'],\n",
    "]\n",
    "\n",
    "board3 = [\n",
    "    ['O', 'X', 'O'], ['', 'O', 'X'], ['X', 'X', 'O'],\n",
    "]\n",
    "\n",
    "board4 = [\n",
    "    ['X', 'X', 'X'], ['O', 'X', 'O'], ['O', '', 'O'],\n",
    "]\n",
    "\n",
    "board5 = [\n",
    "    ['X', 'X', 'O'], ['O', 'X', 'O'], ['X', '', 'O'],\n",
    "]\n",
    "\n",
    "board6 = [\n",
    "    ['X', 'X', 'O'], ['O', 'X', 'O'], ['X', '', ''],\n",
    "]\n",
    "\n",
    "board7 = [\n",
    "    ['X', 'X', 'O', ''], ['O', 'X', 'O', 'O'], ['X', '', '', 'O'], ['O', 'X', '', '']\n",
    "]\n",
    "\n",
    "\n",
    "def eta(first_stop, second_stop, route_map):\n",
    "    '''ETA.\n",
    "    25 points.\n",
    "\n",
    "    A shuttle van service is tasked to travel along a predefined circlar route.\n",
    "    This route is divided into several legs between stops.\n",
    "    The route is one-way only, and it is fully connected to itself.\n",
    "\n",
    "    This function returns how long it will take the shuttle to arrive at a stop\n",
    "    after leaving another stop.\n",
    "\n",
    "    Please see \"mod-4-ipa-1-sample-data.py\" for sample data. The route map will\n",
    "    adhere to the same pattern. The route map may contain more legs and more stops,\n",
    "    but it will always be one-way and fully enclosed.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    first_stop: str\n",
    "        the stop that the shuttle will leave\n",
    "    second_stop: str\n",
    "        the stop that the shuttle will arrive at\n",
    "    route_map: dict\n",
    "        the data describing the routes\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    int\n",
    "        the time it will take the shuttle to travel from first_stop to second_stop\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "import pandas as pd\n",
    "\n",
    "legs_1 = {\n",
    "    (\"upd\", \"admu\"): {\n",
    "        \"travel_time_mins\": 10\n",
    "    },\n",
    "    (\"admu\", \"dlsu\"): {\n",
    "        \"travel_time_mins\": 35\n",
    "    },\n",
    "    (\"dlsu\", \"upd\"): {\n",
    "        \"travel_time_mins\": 55\n",
    "    }\n",
    "}\n",
    "\n",
    "legs_2 = {\n",
    "    ('a1', 'a2'): {\n",
    "        'travel_time_mins': 10\n",
    "    },\n",
    "    ('a2', 'b1'): {\n",
    "        'travel_time_mins': 10230\n",
    "    },\n",
    "    ('b1', 'a1'): {\n",
    "        'travel_time_mins': 1\n",
    "    }\n",
    "}\n",
    "\n",
    "\n",
    "leg = {**legs_1, **legs_2}\n",
    "leg_df = pd.DataFrame.from_dict(legs, orient='index').reset_index()\n",
    "leg_df.columns = ['start_stop', 'end_stop', 'travel_time_mins']\n",
    "def eta(first_stop, second_stop, leg_df):\n",
    "    forward_legs = leg_df.loc[(leg_df['start_stop'] == first_stop) & (leg_df['end_stop'] == second_stop)]\n",
    "    if forward_legs.empty:\n",
    "        two_stops = leg_df.loc[leg_df['start_stop'] == first_stop, 'end_stop'].values\n",
    "        eta_times = []\n",
    "        for two_stop in two_stops:\n",
    "            leg1_duration = eta(first_stop, two_stop, leg_df)\n",
    "            leg2_duration = eta(two_stop, second_stop, leg_df)\n",
    "            eta_times.append(leg1_duration + leg2_duration)\n",
    "        return min(eta_times)\n",
    "    return forward_legs['travel_time_mins'].values[0]"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
